# config/lifecycle_mgr_slam.yaml
#
# Lifecycle manager configuration for SLAM toolbox

/**:
  ros__parameters:
    autostart: True
    node_names: ['slam_toolbox']
    bond_timeout: 5.0
    attempt_respawn_reconnection: true
    bond_respawn_max_duration: 10.0
